### ISSUE TITLE
Interface for shot ordered data

### ISSUE THREAD

**Issue by salwon** [equinor/segyio#316]
I wrote a small class that builds a cleaner interface for shot data. There's not that much to it - it works pretty quickly, and gets you shots however you need them. There aren't any checks to make sure the data are truly shot-ordered, that should be easy enough to build in if someone wants it.

Eventually I would like this to generate a pipeline to Devito or something similar, so RTMs/FWIs can be run from the SEGY directly without much effort. Let me know if you find it useful, or if you see any changes needed before committing it.

Here's a tutorial that walks through the basics.
https://github.com/salwon/segyio/blob/master/python/examples/SegyIO_Shots_Tutorial.ipynb

If you think this will be useful, I'll create the pull request.

**Comment by jokva** [comment]
Hi Stephen,

Great work and a nice demo! I think this fits nicely in the tools module, because _sufficiently_ few files are shot ordered, and at that point it isn't that much different from accessing raw traces (as you do point out, more or less).

I think it's a very useful feature, but I think the implementation and design itself has to be changed a little bit. The class approach is somewhat heavy, and I believe it would benefit from decomposing the problem slightly.

So this is what I propose:

* source/receiver x/y can really be moved out and be either a separate function, or a separate object. I suspect reading X/Ys are useful outside of shots, and that shots are interesting without X/Y.
* traces-per-shot is already a part of the associated data's structure/metadata, 
* get-all-shots should not be a named method, but container protocols should work as expected instead.
* I think the implementation can be simplified with the `attributes` feature, although I am not sure about the performance implications.

It's up to you whether or not you want to implement this yourself, or you can defer it to me. I'll be available for all kinds of assistance if you want to implement it yourself (hit me up on swung!).

Regardless, we'd welcome the PR for sure.

**Comment by MathiasAlerini** [comment]
hi,
if easy/not done I would also generalize for receiver, CMP (default), and offset sortings. Receiver sorting can be as interesting as shot sorting for OBC/OBN data.

**Comment by jokva** [comment]
Experimental support is merged into master and release, so I'll close this issue now.

Thanks for this valuable contribution, Stephen.
