### ISSUE TITLE
Interoperability with vtki

### ISSUE THREAD

**Issue by banesullivan** [equinor/segyio#352]
I'd like to develop functionality to visualize 3D SEG-Y volumes loaded from `segyio` using [`vtki`](https://github.com/akaszynski/vtki). I thought a good place to start would be to work with the [open datasets on the SEG wiki](https://wiki.seg.org/wiki/Open_data). After searching through the docs (*briefly*) I didn't see an example of loading a 3D volume like some of the files given on the SEG Wiki.

Could someone give me some sample code to load one or a few of those files and some direction on what objects in `segyio` I will want to access to retrieve the spatial reference and data attributes? Once I have this direction, I can start making a direct interface to spatially referenced datasets via `vtki` and visualize these volumes.

**Comment by jokva** [comment]
Presumably this is all ok, so I'll close this issue. Please reopen if I'm wrong.

**Comment by alex-orca** [comment]
Hi jokva,
I am having issues when opening many of the datasets on the SEG wiki. Eg. when loading the OPUNAKE-3D segy file from the link above I get the error 'ValueError: Inlines inconsistent, expect all inlines to be unique' if ignore_geometry is False. 
Is this because these files do not have the correct structure anywhere in them? Is there a procedure I can follow to find the location of iline and xline to allow me to load them with ignore_geometry=False? Is there a guide anywhere explaining the structures of these files?
Thanks for any help!
