### ISSUE TITLE
Attributes of little endian file

### ISSUE THREAD

**Issue by ar4** [equinor/segyio#368]
There may be an issue with reading attributes from a little endian file. I have one and, after opening with `endian='little'`,
```
s.attributes(segyio.TraceField.TRACE_SAMPLE_INTERVAL)[6]
```
gives
```
array([65601535], dtype=int32)
```
Opening the file with Seismic Un*x correctly shows `dt=1000`, and
```
s.header[6]
```
also shows `TRACE_SAMPLE_INTERVAL: 1000`.

Some of the other fields are read correctly by `attributes`, however, such as `SourceX`.

**Comment by jokva** [comment]
Wait, is this a seismic unix file, or a SEG-Y? How do you open it, exactly?

**Comment by jokva** [comment]
I wasn't immediately able to reproduce, I'm afraid, so I'll have to poke a bit more around. I quickly checked the read-attribute function and it is, as far as I can tell from a glance, endian aware.

**Comment by jokva** [comment]
I did some more testing after some sleep, and I seem to observe the same behaviour on a little-endian file here. I'll investigate some more.

**Comment by jokva** [comment]
https://github.com/equinor/segyio/pull/369

So the test I did on my machine seems to work - you're free to pull these changes and see if it solves your issue. If the tests go through I'll build a new release with this change applied so it's available upstream.

Thanks for the report - since your analysis was rather thorough, and pinpointed the issue was local to only a few words and only to the `attributes` feature, hunting down the bug was a fairly quick task, at least after some sleep.

**Comment by ar4** [comment]
I confirm that it now reads `dt` correctly. Many thanks!

**Comment by jokva** [comment]
Alright, great. It should be on pypi in half an hour or so.

**Comment by ar4** [comment]
There might unfortunately still be an issue. `header` reports `SourceGroupScalar: -10`, but `attributes` gives `array([65526], dtype=int32)`. What a pity SEG-Y doesn't specify that everyone must use the same endianness!

**Comment by jokva** [comment]
No, I think it's just another bug. We read too much data in the case of short words. I have reproduced (and it was terrible of me not to check that in the first place). A fix should be ready soon.

**Comment by jokva** [comment]
There we go @ar4 

https://github.com/equinor/segyio/pull/370

My hunch for the bug was wrong, but the true source was right next to it. I kinda forgot we use __builtin_bswap when available, and it communicates in unsigned-int, integer removes the sign without an explicit cast.

The hint is, I guess, the fact that -10 2s-complement and 65526 unsigned have the same bitwise representation.

**Comment by ar4** [comment]
I confirm that it now reads `SourceGroupScalar` correctly. Many thanks!
