### ISSUE TITLE
SEGY files created always have `samples`  starting from zero.

### ISSUE THREAD

**Issue by whimian** [equinor/segyio#397]
I tried to create a SEGY file in the same way as https://github.com/equinor/segyio/blob/master/python/examples/make-file.py. 

The `samples` attribute in the `spec` always starts with zero, even when I explicitly gave it a range that starts with a non-zero integer.

I'm not sure if it's a bug. or there's some other workaround.

**Comment by jokva** [comment]
Well, it's a consequence of segyio not really assuming too much for you.

If you inspect the samples attribute of the newly-created file it should respect your samples. However, samples are calculated from the delay-recording-time header word, which as to be set per-trace. My guess is you don't set this to anything non-zero, which is why when you open it again the file starts at zero.

If you set that header word in your traces, you should see your traces start at your non-zero first time.

**Comment by jokva** [comment]
In short, remember to do `f.header[i][segyio.su.delrt] = spec.samples[0]`

**Comment by whimian** [comment]
@jokva Thank you
