### ISSUE TITLE
create a new segy crop

### ISSUE THREAD

**Issue by StefosGeo** [equinor/segyio#400]
Hello,

I am trying to create a segy file from scratch using this example 
https://github.com/equinor/segyio/blob/master/python/examples/make-file.py

I want the samples start counting for example from 900 not from zero. So I tried this
`spec.samples = range(900,1950,3)`

but in the end the output segy file has sapmling counting from 0 with step 3.

Thanks

**Comment by jokva** [comment]
Hi,

whimian just struggled with the same thing: https://github.com/equinor/segyio/issues/397

The short answer is that segyio doesn't write headers for you by default, because it assumes you want to add more information to them which would trigger a write _anyway_, so you need to manually set the delay-recording-time header word.
