### ISSUE TITLE
Feature request: support custom trace headers. 

### ISSUE THREAD

**Issue by superzappie** [equinor/segyio#430]
I would like to see support for custom trace headers. EG, a 2 byte trace header in the offset region 180-240. Is this a feature that could ever be implemented in segyio?

**Comment by jokva** [comment]
180-240 is a bit more than two bytes, so I'm not 100% sure that I get what you mean.

With the current approach to header words, this is not really easily supported - it's a pretty hard assumption currently that header words are at the positions (but not necessarily with the semantics) specified by the standard. This is a problem now and again (but honestly because the file is _super_ broken), and would be addressed with a major revision of segyio.

**Comment by GGDRriedel** [comment]
+ Segy-Files are an absolute clusterfuck most of the time, I would rather NOT have people write stuff wherever they want. It's really time to stop supporting conventions that were made when stuff was still written to tape in the field.
