### ISSUE TITLE
Sample count limitation with tools.from_array2D()

### ISSUE THREAD

**Issue by valentinmetraux** [equinor/segyio#461]
Impossible to create segy with more than uint16 samples/traces from segyio.tools.from_array2D.

Works fine on short traces but got the following error message with longer ones:
![image](https://user-images.githubusercontent.com/13730734/81408051-c953d080-913c-11ea-89fb-3de8f95338ef.png)

**Comment by jokva** [comment]
This is slightly more involved than I first pictured, since >64k samples means using a completely new header word, which segyio is unaware of. The fix should be fairly quick still, but requires more testing.

https://seg.org/Portals/0/SEG/News%20and%20Resources/Technical%20Standards/seg_y_rev2_0-mar2017.pdf

**Comment by jokva** [comment]
Fixed in https://github.com/equinor/segyio/pull/463
